### ISSUE TITLE
Add buildscript and gradle folder

### ISSUE THREAD

**Issue by kada49** [anastarawneh/GuildBridgeClient#1]
Could you also please upload the buildscript file and the gradle folder + content?

**Comment by anastarawneh** [comment]
Done: [`76cd6b6`](https://github.com/anastarawneh/GuildBridgeClient/commit/76cd6b6d100aa7539eddd99c73606c2d01714b02)

I can't remember why I explicitly included them in .gitignore, but they're uploaded now.
